spring.application.name=stockapp

# spring.thymeleaf.check-template-location=false

spring.datasource.url=jdbc:postgresql://10.225.16.8:5432/dbaluarte
spring.datasource.username=postgres
spring.datasource.password=domingo14

# spring.datasource.url=jdbc:postgresql://localhost:5433/dbaluarte
# spring.datasource.username=postgres
# spring.datasource.password=sybilti

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging para ver las consultas SQL y los parámetros
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE
# Clave secreta para firmar los tokens JWT. Debe ser larga y compleja (mínimo 256 bits / 32 caracteres).
jwt.secret=c3R1Y2tBcHAtc2VjcmV0LWtleS1mb3Itand0LXNpZ25pbmctbXVzdC1iZS1sb25nZXI=
